name: Setup Repositories

on:
  schedule:
    - cron: '2 0 * * *' # Runs every day at 02:00 a.m. UTC
  workflow_dispatch:

jobs:
  setup_repositories:
    runs-on: ubuntu-latest
    env:
      JSON_REPOSITORY_LIST: ./01_repo_setup/json/repository_list.json
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Setup Repositories
        uses: ./01_repo_setup/python/repo_setup
        with:
          json_repository_list: ${{ env.JSON_REPOSITORY_LIST }}
        secrets:
          github_token: ${{ secrets.REPO_SETUP_TEST_TOKEN  }}