name: Setup Repositories

on:
  schedule:
    - cron: '2 0 * * *' # Runs every day at 02:00 a.m. UTC
  workflow_dispatch:

jobs:
  setup_repositories:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Repositories
        uses: ./python/repo-setup
        with:
          json_repository_list: ./json/repository_list.json