name: Setup Repositories

on:
  schedule:
    - cron: '2 0 * * *' # Runs every day at 02:00 a.m. UTC
  workflow_dispatch:

jobs:
  setup_repositories:
    runs-on: ubuntu-latest
    env:
      REPO_SETUP_ACTION: ./01_repo_setup/python/repo_setup
      JSON_REPOSITORY_LIST: ./01_repo_setup/json/repository_list.json
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Troubleshoot
        shell: bash
        run: |
          echo "Current Working Directory:"
          pwd
          echo "List Files:"
          ls -la
          echo "Python Version:"
          python --version

      - name: Setup Repositories
        uses: ${{ env.REPO_SETUP_ACTION }}
        with:
          json_repository_list: ${{ env.JSON_REPOSITORY_LIST }}